.github/workflows/sphinx_build_deploy.yml
docs/source/index.rst
examples/notebooks/Grid_Levels_and_Parameters.ipynb

Several small-ish updates to the python-awips website:
- .github/workflows/sphinx_build_deploy.yml:
- changed the branch to trigger on from "master" to "main" since we renamed the default branch
- docs/source/index.rst
- changed "geometry" to "geographic" in opening description
- Added a section for pre-req software (python3, conda, git)
- Added distinct sections with subsections for the Package-Only Install and the Source Code with Examples Install
- Added a section for Contact Us with our support email
- Removed all unnecessary duplicate sections (Requirements, Quick Example, and Contents)
- Made the toctree hidden
- examples/notebooks/Grid_Levels_and_Parameters.ipynb
- Removed the reference to the word "DAF"

Website updates

---

examples/notebooks/Grid_Levels_and_Parameters.ipynb
examples/notebooks/Grids_and_Cartopy.ipynb

- replaced table of auto-table of contents with a manual one with external links
- replaced all "top" links with external links
- changed header slightly and removed unidata logo
- updated the "Related Notebooks links"
Changed the name of the AWIPS_Grids_and_Cartopy notebook:
- removed the preceeding "AWIPS" since that's not in any of our other notebooks

Changes to Grid Levels and Params notebook:

---

examples/notebooks/Grid_Levels_and_Parameters.ipynb

- update links to remove numbers in the subsection links (these are not needed)

Website - Grid Levels and Params page

---

examples/notebooks/Grids_and_Cartopy.ipynb

- added the image preview to the header of the notebook
- fixed spelling mistake in subheader "Documentation"

Small changes to grids and cartopy notebook:

---

.github/workflows/sphinx_build_deploy.yml

- add the ability to trigger the action on a workflow_dispatch

Action update

---

environment.yml

- add the nbextensions dependency so table of contents widget will display for notebooks with new template

Add one dependency to environment.yml

---

examples/notebooks/Colorized_Grid_Data.ipynb

- now named "Colorized Grid Data"

Changed the name of the "Grids and Cartopy" notebook:

---

examples/notebooks/Colorized_Grid_Data.ipynb

- changing the name broke all the TOC and "top" links, so this is a commit fixing those

Update links on Colorized Grid Data notebook

---

examples/notebooks/Grid_Levels_and_Parameters.ipynb
examples/notebooks/METAR_Station_Plot_with_MetPy.ipynb

- updated the Grid Levels and Parameters notebook because there was a leftover admonition style note that had not been changed for the website
- updated the Metar notebook for a "note" that had not been changed over

Small changes to website notebooks for "Note" styling

---

examples/notebooks/Model_Sounding_Data.ipynb

- fix broken link in toc
- reformat See also section to work for website rendering

Small changes for Model Sounding Notebook (website)

---

examples/notebooks/Model_Sounding_Data.ipynb

- added more links in the see also section for additional metpy documentation

Small change to the model sounding notebook

---

examples/notebooks/Model_Sounding_Data.ipynb

- added additional links for metpy documentation in the See Also section

Small modification to the Model sounding notebook

---

examples/notebooks/Regional_Surface_Obs_Plot.ipynb

- update to maps request cell (remove redundancy)

Regional Obs notebook (website branch)

---

examples/notebooks/Regional_Surface_Obs_Plot.ipynb

- Remove unnecessary line from maps request cell

Regional Surface obs notebook

---

examples/notebooks/Regional_Surface_Obs_Plot.ipynb

Regional Surface obs notebook (website branch)

---

examples/notebooks/Upper_Air_BUFR_Soundings.ipynb

- fix two broken links
- proper capitalization on a subsection

Small updates to Upper Air BUFR sounding notebook

---

examples/notebooks/Upper_Air_BUFR_Soundings.ipynb

- fix a note for the website rendering

Change to Upper Air BUFR Soundings notebook

---

examples/notebooks/Upper_Air_BUFR_Soundings.ipynb

-change capitalization of a subsection

Upper Air BUFR Sounding notebook

---

examples/notebooks/Forecast_Model_Vertical_Sounding.ipynb

- add table of contents
- fix broken "top" link

Website version - Forecast Model sounding notebook fixes

---

environment.yml
setup.py

- remove jupyter_contrib_nbextensions package from environment.yml as this is no longer supported
- update the version in the setup.py file so when installing locally it has v20 associated with it
- remove download link from the setup.py file since it's not correct for the beta
- remove six dependency from setup.py since we no longer have any Python2 code

Updated the environment.yml and setup.py files

---

docs/source/index.rst

- add an "important" admonition to the homepage about the beta installation
- add a beta installation section at the bottom of the homepage

Update documentation with beta install instructions

---

dynamicserialize/adapters/EnumSetAdapter.py

- don't use bufferset in EnumSetAdapter, just keep it as set, works properly that way

Remove change that copied MJ
